#ifndef CONFIG_H
#define CONFIG_H

// KERNEL HEAP
#define BOBAOS_KERNEL_HEAP_TABLE_ADDRESS 0x500
#define BOBAOS_KERNEL_HEAP_ADDRESS 0x500000
#define BOBAOS_KERNEL_HEAP_SIZE 1024 * 1024 * 100 //100MB kernel heap

// GDT
#define BOBAOS_KERNEL_SELECTOR_CODE 0x8
#define BOBAOS_KERNEL_SELECTOR_DATE 0x10
#define BOBAOS_GDT_ENTRIES 3

//IDT
#define BOBAOS_TOTAL_INTERRUPTS 256

#endif
