#ifndef CONFIG_H
#define CONFIG_H

//PCI
#define BOBOAOS_MAX_PCI_DEVICES 0xF

// MEMORY
#define BOBAOS_MEMORY_MAP_MAX_ENTRIES 0xF

#define BOBAOS_USE_BUDDY_FOR_KERNEL_HEAP 0		//Change this to 1 and the kernel will use the buddy algorithm

// KERNEL HEAP BUDDY
#define BOBAOS_KERNEL_HEAP_SMALLEST_PAGE 0x400	//1KB
#define BOBAOS_KERNEL_HEAP_BIGGEST_PAGE 0x20000 //128KB

// KERNEL HEAP
#define BOBAOS_KERNEL_HEAP_TABLE_ADDRESS 0x0
#define BOBAOS_KERNEL_HEAP_ADDRESS 0x500000
#define BOBAOS_KERNEL_HEAP_SIZE 1024 * 1024 * 100 //100MB kernel heap

// GDT
#define BOBAOS_KERNEL_SELECTOR_CODE 0x8
#define BOBAOS_KERNEL_SELECTOR_DATE 0x10
#define BOBAOS_GDT_ENTRIES 3

// IDT
#define BOBAOS_TOTAL_INTERRUPTS 256

// KOAL
#define BOBAOS_MAX_KOAL_ENTRIES 12

//DISK
#define BOBAOS_MAX_DISK_DRIVER 12
#define BOBAOS_MAX_DISKS 255

//FILE SYSTEM LAYER
#define BOBAOS_MAX_FILESYSTEMS 12
#define BOBAOS_MAX_PATH_SIZE 255
#define BOBAOS_MAX_OPEN_FILES 1024

//AHCI
#define BOBAOS_MAX_AHCI_PRDT_ENTRIES 8

#endif
