FROM xddc/bobaos:base-latest

USER containeruser

EXPOSE 5900/tcp
EXPOSE 5900/udp

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
	x11vnc xvfb \
	xfce4 xfce4-goodies

RUN mkdir ~/.vnc && \
	x11vnc -storepasswd containeruser ~/.vnc/passwd

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
