FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
	vim \
	git \
	gdb \
	sudo \
	curl ca-certificates \
	build-essential bison flex\
	libgmp3-dev libmpc-dev libmpfr-dev\
	texinfo libisl-dev \
	binutils \
	qemu-system-x86 \
	nasm \
	iproute2

COPY container/Base/build_gcccc.sh /buildgcccc.sh

RUN chmod +x /buildgcccc.sh && /buildgcccc.sh

RUN adduser containeruser && adduser containeruser sudo && passwd -d containeruser

#RUN echo "containeruser ALL=NOPASSWD: /usr/bin/apt-get install" >> /etc/sudoers

USER containeruser

WORKDIR /home/containeruser

ENTRYPOINT /bin/bash
