FROM debian:bookworm-slim

ENV targ=x86_64-elf

RUN apt-get update && apt-get install -y --no-install-recommends \
	vim \
	git \
	gdb \
	qemu-system-x86 \
	nasm \
	iproute2

RUN adduser containeruser && adduser containeruser sudo

USER containeruser

WORKDIR /home/containeruser

ENTRYPOINT /bin/bash