name: Docker Image CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: dockerHub login
      run: docker login -u xddc -p ${{secrets.dockerhub}}
      
    - uses: actions/checkout@v4
    - name: Build the Base Docker image
      run: docker build . -f ./container/Base/Dockerfile_base --tag xddc/bobaos:base-latest && docker push xddc/bobaos:base-latest
      
    - uses: actions/checkout@v4
    - name: Build the Develop Docker image
      run: docker build . --file ./container/Develop/Dockerfile_dev --tag xddc/bobaos:develop-latest && docker push xddc/bobaos:develop-latest
